name: Deploy Github Pages

on:
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@4.0.2
        with:
          version: 20.x
      
      - name: Checkout branch
        uses: actions/checkout@4.1.2
      
      - name: Run deploy script
        run: npm run deploy
