name: Deploy Github Pages

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
      
      - name: Checkout branch
        uses: actions/checkout@v4.1.2

      - name: Install dependencies
        run: npm i

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
          
